# Generated by Django 2.2.2 on 2020-05-25 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='roles',
            field=models.CharField(choices=[('doctor', 'DOCTOR'), ('patient', 'PATIENT')], default='doctor', max_length=10, verbose_name='Register as '),
        ),
    ]
