# Generated by Django 2.2.2 on 2020-05-25 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20200525_0806'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='roles',
            field=models.CharField(choices=[('doctor', 'DOCTOR'), ('patient', 'PATIENT')], default='doctor', max_length=10, verbose_name='Register as'),
        ),
    ]
