# Generated by Django 2.2.2 on 2020-05-26 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20200525_1508'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='roles',
            field=models.CharField(choices=[('patient', 'PATIENT'), ('doctor', 'DOCTOR'), ('receptionist', 'RICEPTIONIST'), ('hr', 'HR')], default='patient', max_length=10, verbose_name='Register as'),
        ),
    ]
