# Generated by Django 2.2.2 on 2020-05-26 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20200526_1934'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='roles',
            field=models.CharField(choices=[('patient', 'PATIENT'), ('doctor', 'DOCTOR'), ('hr', 'HR'), ('receptionist', 'RECEPTIONIST')], default='patient', max_length=15, verbose_name='Register as'),
        ),
    ]
