# Generated by Django 2.2.2 on 2020-05-25 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='roles',
        ),
        migrations.AddField(
            model_name='patient',
            name='blood_group',
            field=models.CharField(choices=[('o+', 'O+ TYPE'), ('o-', 'O- TYPE'), ('a+', 'A+ TYPE'), ('a-', 'A- TYPE'), ('b+', 'B+ TYPE')], default='o+', max_length=10, verbose_name='Blood Group'),
        ),
    ]
