# Generated by Django 2.2.2 on 2020-05-26 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0004_auto_20200526_2133'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'MALE'), ('female', 'FEMALE'), ('others', 'OTHERS')], default='male', max_length=10, null=True, verbose_name='Gender '),
        ),
        migrations.AlterField(
            model_name='patient',
            name='blood_group',
            field=models.CharField(choices=[('o+', 'O+ TYPE'), ('o-', 'O- TYPE'), ('a+', 'A+ TYPE'), ('a-', 'A- TYPE'), ('b+', 'B+ TYPE')], default='o+', max_length=10, verbose_name='Blood Group '),
        ),
    ]
