# Generated by Django 2.2.2 on 2020-05-26 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0005_auto_20200526_2143'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='is_female',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='is_male',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='is_other',
        ),
        migrations.AlterField(
            model_name='patient',
            name='age',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='case_paper',
            field=models.IntegerField(blank=True, null=True, verbose_name='Case Paper'),
        ),
    ]
