# Generated by Django 2.2.2 on 2020-05-26 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0006_auto_20200526_2201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='blood_group',
            field=models.CharField(choices=[('O+', 'O+ TYPE'), ('O-', 'O- TYPE'), ('A+', 'A+ TYPE'), ('A-', 'A- TYPE'), ('B+', 'B+ TYPE')], default='o+', max_length=10, verbose_name='Blood Group '),
        ),
        migrations.AlterField(
            model_name='patient',
            name='gender',
            field=models.CharField(blank=True, choices=[('Male', 'MALE'), ('Female', 'FEMALE'), ('Others', 'OTHERS')], default='male', max_length=10, null=True, verbose_name='Gender '),
        ),
    ]
