# Generated by Django 2.2.2 on 2020-05-25 12:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('doctor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=50)),
                ('is_male', models.BooleanField(default=False, verbose_name='Male')),
                ('is_female', models.BooleanField(default=False, verbose_name='Female')),
                ('is_other', models.BooleanField(default=False, verbose_name='Other')),
                ('age', models.IntegerField(default=20)),
                ('address', models.CharField(max_length=100)),
                ('blood_group', models.CharField(choices=[('o+', 'O+ TYPE'), ('o-', 'O- TYPE'), ('a+', 'A+ TYPE'), ('a-', 'A- TYPE'), ('b+', 'B+ TYPE')], default='o+', max_length=10, verbose_name='Blood Group')),
                ('medical_report', models.ImageField(upload_to='patient/images')),
                ('case_paper', models.IntegerField(default=1, verbose_name='Case Paper')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
