# Generated by Django 2.2.2 on 2020-05-26 20:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0003_auto_20200526_2318'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='salary',
            field=models.IntegerField(blank=True, null=True, verbose_name='Salary '),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='patient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='patient.Patient'),
        ),
    ]
